### ISSUE TITLE
error: NoSuchKeyException cannot be found by . On Amazon servers

### ISSUE THREAD

**Issue by jojeda-four-id** [devcoffee/s3storage_idempiere#1]
Hi, good morning. I'm having the NoSuchKeyException error in iDempiere applications that are installed on Amazon.
while on local development machines it does not happen.

This error occurs when executing the Migrate Storage Provider process

![Captura de pantalla de 2023-09-04 10-33-21](https://github.com/devcoffee/idempiere-s3storage/assets/67495969/1e7403cb-fd2e-4c09-8fc3-0edde143f384)

```
11:58:34.963===========> MigrateStorageProvider.process: software/amazon/awssdk/services/s3/model/NoSuchKeyException [199]
java.lang.ClassNotFoundException: software.amazon.awssdk.services.s3.model.NoSuchKeyException cannot be found by org.devcoffee.idempiere.s3storage_1.0.0.202308311706
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:529)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:524)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	at org.devcoffee.idempiere.s3storage.model.AttachmentS3Compatible.save(AttachmentS3Compatible.java:174)
	at org.compiere.model.MAttachment.saveLOBData(MAttachment.java:499)
	at org.compiere.model.MAttachment.beforeSave(MAttachment.java:524)
	at org.compiere.model.PO.save(PO.java:2263)
	at org.compiere.model.PO.saveEx(PO.java:2441)
	at org.idempiere.process.MigrateStorageProvider.migrateAttachments(MigrateStorageProvider.java:256)
	at org.idempiere.process.MigrateStorageProvider.doIt(MigrateStorageProvider.java:214)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:256)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:164)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:173)
	at org.compiere.apps.AbstractProcessCtl.startProcess(AbstractProcessCtl.java:367)
	at org.compiere.apps.AbstractProcessCtl.run(AbstractProcessCtl.java:208)
	at org.adempiere.webui.apps.WProcessCtl.process(WProcessCtl.java:208)
	at org.adempiere.webui.apps.AbstractProcessDialog$ProcessDialogRunnable.doRun(AbstractProcessDialog.java:1142)
	at org.adempiere.util.ContextRunnable.run(ContextRunnable.java:38)
	at org.adempiere.webui.apps.DesktopRunnable.run(DesktopRunnable.java:40)
```

**Comment by muriloht** [comment]
hi @jojeda-four-id looks that some dependency jar is missing in your final bundle

i tried here a migration process with some attachments and everything wen fine

if you are still facing some problem, please provide more info then i try to help you
